### ISSUE TITLE
在rails的摸索过程中

### ISSUE THREAD

**Issue by Wellaiyo** [Wellaiyo/demo_app#1]
@happypeter

**Comment by Wellaiyo** [comment]
还有一个问题就是：我在环境变量里加上了sublime-text这个文件，所以我能打开sublime，但是sublime-text太长了　，我想直接输入sub就能打开sublime-text怎么办？

**Comment by happypeter** [comment]
.bashrc 中设置 alias 就好了

**Comment by Wellaiyo** [comment]
给指条明路吧，快不知所措了。控制器、视图、模型之间是如何交互处理的？实在让人迷糊。我指的是具体代码实现这方面

**Comment by happypeter** [comment]
@Wellaiyo  先不要碰 rails ，先写一个最简单的 ruby 小程序吧，里面要包含 module class method， 继承... 这些基本概念。

**Comment by Wellaiyo** [comment]
差不多了 ，你可以去看看我的github page ，我的进度都在里面 。，它以后会是我的技术博客。
如果我哪些地方写错了，对某些东西理解错误了，请在issue里@我。
那么，我接下来该怎么做？

**Comment by happypeter** [comment]
牛！那下面可以按照 http://www.imooc.com/view/230 走一下，有不明白的地方可以问，但是问题要具体一些，描述要详细一些，下面这样提问太笼统，不好回答

>控制器、视图、模型之间是如何交互处理的？

**Comment by Wellaiyo** [comment]
你有没有觉得那么page里的disqus评论插件不太好用 ，我已经很久没加载成功过它了

**Comment by happypeter** [comment]
确实有时候加载很慢。不过国内也没有听说有对等的服务可以替代

**Comment by Wellaiyo** [comment]
国内的应该没有相应的服务能对接Gmail这些国外企业，但是我还是换成了“友言” ，毕竟加载快，国内用这个还是比较好的

**Comment by happypeter** [comment]
挺好，学习了
